[[redirects]]
  from = "/album-1/1"
  to = "https://lh3.googleusercontent.com/pw/AP1GczPchYZ4qy2fEKn8sUKYDgwkE6riisrUP2sdNEO93DcKuGIAtl1dars5wdnDEgfk1--51QQbAmcjLGGwl458qBQba2JcTO75LIAkqpJfxSVCBcpRSJu_hf4gqZRpDlH-YMrtiZ-OrhSpw3kQYf3hWd8h_A=w1332-h984-s-no-gm"
  status = 200
  force = true

[[redirects]]
  from = "/qr"
  to = "https://thiennguyen.dev/about/#qr-collection"
  status = 301
  force = true

[[redirects]]
  from = "/"
  to = "https://thiennguyen.dev"
  status = 301
  force = true

[[redirects]]
  from = "/*"
  to = "https://thiennguyen.dev"
  status = 301
  force = true
