[[redirects]]
  from = "/old-path"
  to = "https://photos.fife.usercontent.google.com/pw/AP1GczMDD4kPUozzda3i34uKB3mw9XUYhU0ayWczxDed3HekQguzHu4MWS3Kvw=w1332-h984-s-no-gm?authuser=1"
  status = 301
  force = true

[[redirects]]
  from = "/qr"
  to = "https://thiennguyen.dev/about/#qr-collection"
  status = 301
  force = true

[[redirects]]
  from = "/"
  to = "https://thiennguyen.dev"
  status = 301
  force = true

[[redirects]]
  from = "/*"
  to = "https://thiennguyen.dev"
  status = 301
  force = true
